config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "stocks#index"

  resources :users, only: [:show, :edit, :update]
  resources :stocks do

    member do
      patch :archive
      patch :unarchive
      post :add_image
      delete :remove_image
      # post :add_pdf
      # delete :remove_pdf
    end

    collection do
      get :history
    end

    resources :memos, only: [:create, :destroy]
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/memo.rb
class Memo < ApplicationRecord
    belongs_to :stock
end

app/models/stock.rb
class Stock < ApplicationRecord
    after_initialize :set_default_status, if: :new_record?

    belongs_to :user
    has_many :memos, dependent: :destroy
    has_many_attached :images
    has_many_attached :pdfs
  
    enum status: {active: 0, archived: 1}
    validates :status, inclusion: { in: statuses.keys }
    validates :ticker, presence: true
    validates :images, content_type: ['image/png', 'image/jpg', 'image/jpeg', 'image/gif']
    # validates :pdfs, attached: true, content_type: ['application/pdf']
  
    private
  
    def set_default_status
      self.status ||= :active
    end
    
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    before_action :basic_auth

    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    def basic_auth
        authenticate_or_request_with_http_basic do |username, password|
            username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
        end
    end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController

    def index
        @memos = Memo.order(created_at: :desc)
    end

    def new
    end

    def create
      @stock = Stock.find(params[:stock_id])
      @memo = @stock.memos.build(memo_params)
  
      if @memo.save
        render json: { memo: @memo.as_json.merge({ created_at: @memo.created_at.utc.iso8601 }) }, status: :created
      else
        render json: { errors: @memo.errors.full_messages }, status: :unprocessable_entity
      end
    end

    def destroy
      @stock = Stock.find(params[:stock_id])
      @memo = Memo.find(params[:id])
      @memo.destroy
      redirect_to stock_path(@stock)
    end

    
      private
    
      def memo_params
        params.require(:memo).permit(:content)
      end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    before_action :set_stock, only: [:show, :edit, :update, :destroy, :archive, :unarchive]
    before_action :authenticate_user!
  
    def index
      @user = current_user
      @stocks = Stock.active
      @new_stock = Stock.new
      @memo = Memo.new
      if params[:id].present?
        @stock = Stock.find(params[:id])
        @memos = @stock.memos
      end
    end

    def history
      @user = current_user
      @archived_stocks = Stock.archived
    end

    def archive
      @stock.archived!
      redirect_to root_path
    end

    def unarchive
      @stock.active!
      redirect_to history_stocks_path
    end
  
    def create
      query = stock_params[:ticker].blank? ? stock_params[:name] : stock_params[:ticker]
      service = CreateStockService.new(query, stock_params, current_user)
      if service.call
        redirect_to stock_path(service.stock)
      else
        @stock = service.stock || Stock.new(stock_params)
        @stocks = Stock.active
        @user = current_user
        @memo = Memo.new
        flash.now[:alert] = service.error_message
        render :index, status: :unprocessable_entity
      end
    end
  
    def show
      @user = current_user
      @new_stock = Stock.new
      @memo = Memo.new
      @memos = @stock.memos.order(created_at: :desc)
      if params[:origin] == "history"
        @archived_stocks = Stock.archived
      else
        @stocks = Stock.active
      end
    end
  
    def destroy
      @stock.destroy
      redirect_to root_path
    end

    def add_image
      @stock = Stock.find(params[:id])
      @stock.images.attach(params[:stock][:images])
      redirect_to @stock
    end

    def remove_image
      @image = ActiveStorage::Attachment.find(params[:id])
      @image.purge
      redirect_to @image.record
    end

    # def add_pdf
    #   @stock = Stock.find(params[:id])
    #   @stock.pdfs.attach(params[:stock][:pdfs])
    #   if @stock.save
    #     redirect_to @stock, notice: '画像がアップロードされました'
    #   else
    #     redirect_to @stock, alert: '画像のアップロードに失敗しました'
    #   end
    # end

    # def remove_pdf
    #   @pdf = ActiveStorage::Attachment.find(params[:id])
    #   @pdf.purge
    #   redirect_to @pdf.record
    # end
  
    private
  
    def set_stock
      @stock = Stock.find(params[:id])
    end
  
    def stock_params
      params.require(:stock).permit(:name, :ticker, :market, :industry, images: [], pdfs: [])
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def edit
        @user = User.find(current_user.id)
    end

    def update
        if current_user.update(user_params)
            redirect_to root_path
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private

    def user_params
        params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceMemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stocks/_new_stock_form.html.erb
<%= form_with model: new_stock, url: stocks_path, class: "new-stock-form", local: true do |form| %>
        <div class="form-group">
          <%= form.label :ticker %>
          <%= form.text_field :ticker, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= form.submit '+ New Stock', class: "new_stock_link" %>
        </div>
      <% end %>

app/views/stocks/_stock_details.html.erb
<% if @stock %>

<div class="stock-content">
  <div class="stock-header">
    <h2><%= @stock.name %> (<%= @stock.ticker %>)</h2>
    <p> / <%= @stock.market %></p>
    <p> / <%= @stock.industry %></p>
  </div>
  <%# memoの登録 %>
  <% if @stock.active? %>
  <%= form_with model: [@stock, @memo], method: :post, id: "form", data: { stock_id: @stock.id },class:"new-memo-form" do |form| %>
    <%= form.text_area :content, id: "content",class:"new-form-content" %>
    <%= form.submit 'メモ追加', id: "submit",class:"new-form-submit" %>
  <% end %>
  <% end %>

  <div id="list"></div>
  <%# memoの表示 %>
  <% if @memos.present? %>
    <% @memos.each do |memo| %>
      <div class="memo">
        <div class="post-content">
          <%= memo.content %>
        </div>
        <div class="post-date">
          <%= l memo.created_at, format: :long %><%= link_to "削除", stock_memo_path(memo.stock_id,memo.id),data:{ turbo_method: :delete} ,class:"memo-delete" %>
        </div>
      </div>
    <% end %>
  <% end %>

  <%# 画像upload %>
  <%= form_with(model: @stock, url: add_image_stock_path(@stock),method: :post, local: true, class:"add-image-form") do |form| %>
    <label class="form-image">
      <%= image_tag("fileupload_120150.png", class: "add-image-file") %>
      <%= form.file_field :images, direct_upload:true, class: "hidden" %>
    </label>
      <%= form.submit 'ファイルをアップロード', class:"file-upload" %>
  <% end %>
  <%# 画像の表示 %>
  <div class="form-images">
    <% @stock.images.each do |image| %>
      <div class="image">
        <%= image_tag image.variant(resize: '400 x 400') %>
        <div class="image-delete">
          <%= link_to '', remove_image_stock_path(image), data: { turbo_method: :delete }, class:"square_btn" %>
        </div>
      </div>
    <% end %>
  </div>

  <%# PDFの表示 %>
  <% if @stock.pdfs.attached?%>
    <h3>PDFs</h3>
    <% @stock.pdfs.each do |pdf| %>
      <%= link_to pdf.filename.to_s, url_for(pdf) %><br>
    <% end %>
  <% end %>
</div>

<% if !@stock.archived? %>
<div class="details-footer">
  <%= link_to 'topへ', root_path, class: 'root-link' %>

  <%= form_with url: archive_stock_path(@stock), method: :patch, local: true do %>
    <%= submit_tag 'アーカイブする' %>
  <% end %>

  <%= link_to "削除する", stock_path(@stock),data:{ turbo_method: :delete},class:'delete-stock-link' %>
</div>
<% end %>
  
<% else %>

  <div class="stock_nil">
   <p>株式を選んでください</p>
  </div>
<% end %>

app/views/stocks/history.html.erb
<div class="container">
  <div class="row">
    <%# 左側 %>
    <div class="left-content">
      <div class="upper_archived">
        <h2>Archived Stocks</h2>
        <%# 登録された株式一覧 %>
        <ul>
          <% @archived_stocks.each do |archived_stock| %>
            <li>
              <%= link_to "#{archived_stock.ticker} - #{archived_stock.name}", stock_path(archived_stock, origin: 'history'),class:"selected_archive_link" %>
              <%= link_to '戻す', unarchive_stock_path(archived_stock), data: {turbo_method: :patch}, class: 'rtn-active' %>
           </li>
          <% end %>
        </ul>
      </div>

      <div class="lower">
        <div class="user_link">
          <%= link_to "#{current_user.name}さん /" , edit_user_path(@user) %>
          <%= link_to "ログアウト", destroy_user_session_path, data:{turbo_method: :delete} %>
        </div>
        <%= link_to "ホームへ", root_path, class:"index-link" %>
      </div>
    </div>

    <%# 右側 %>
    <div class="right-content">
      <div id="stock-details">
        <%= render 'stock_details' %>
      </div>
    </div>
  </div>
</div>

app/views/stocks/index.html.erb
<div class="container">
  <div class="row">
    <%# 左側 %>
    <div class="left-content">
      <div class="upper">
      <h2>Stocks</h2>
      <%# 新規登録フォーム  %>
        <%= render partial:'new_stock_form', locals: { new_stock: @new_stock} %>
      <ul class="stocks_index">
        <%# 登録された株式一覧 %>
        <% @stocks.each do |stock| %>
          <li><%= link_to "#{stock.ticker} - #{stock.name}", stock_path(stock), class:"selected-stock" %></li>
        <% end %>
      </ul>
      </div>
      <div class="lower">
        <div class="user_link">
          <%= link_to "#{current_user.name}さん /" , edit_user_path(@user) %>
          <%= link_to "ログアウト", destroy_user_session_path, data:{turbo_method: :delete} %>
        </div>
        <%= link_to "アーカイブへ", history_stocks_path, class:"archive-link" %>
      </div>
    </div>

    <%# 右側 %>
    <div class="right-content">
      <div id="stock-details">
        <%= render 'stock_details' %>
      </div>
    </div>
  </div>
</div>

app/views/stocks/show.html.erb
<div class="container">
  <div class="row">
    <div class="left-content">
      <% if params[:origin] == 'history' %>
      <%# historyから遷移の場合 %>
        <div class="upper_archived">
          <h2>Archived Stocks</h2>
          <%# 登録された株式一覧 %>
          <ul>
            <% @archived_stocks.each do |archived_stock| %>
              <li>
                <%= link_to "#{archived_stock.ticker} - #{archived_stock.name}", stock_path(archived_stock),class:"selected_archive_link" %>
                <%= link_to '戻す', unarchive_stock_path(archived_stock), data: {turbo_method: :patch}, class: 'rtn-active' %>
            </li>
            <% end %>
          </ul>
        </div>
      <% else %>
      <%# history以外から遷移の場合 %>
        <div class="upper">
        <h2>Stocks</h2>
        <%# stock新規登録フォーム  %>
        <%= render partial:'new_stock_form', locals: { new_stock: @new_stock} %>
        <ul class="stocks_index">
          <%# 登録された株式一覧 %>
          <% @stocks.each do |stock| %>
            <li><%= link_to "#{stock.ticker} - #{stock.name}", stock_path(stock), class:"selected-stock" %></li>
          <% end %>
        </ul>
        </div>
      <% end %>

      <div class="lower">
        <div class="user_link">
          <%= link_to "#{current_user.name}さん /" , edit_user_path(@user) %>
          <%= link_to "ログアウト", destroy_user_session_path, data:{turbo_method: :delete} %>
        </div>
        <% if params[:origin] == 'history' %>
        <%# historyから遷移の場合 %>
          <%= link_to "ホームへ", root_path, class:"index-link" %>
        <% else %>
        <%# history以外から遷移の場合 %>
          <%= link_to "アーカイブへ", history_stocks_path, class:"archive-link" %>
        <% end %>
      </div>
    </div>

    <%# 右側 %>
    <div class="right-content">
      <div id="stock-details", class="stock-details">
        <%= render 'stock_details' %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h2>アカウント編集</h2>

<%= form_for(@user, html: { method: :put, multipart: true }) do |f| %>
  <div class="form-group">
    <%= f.label :name, "名前" %><br />
    <%= f.text_field :name, autofocus: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email, "メールアドレス" %><br />
    <%= f.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password, "新しいパスワード" %> (6文字以上)<br />
    <%= f.password_field :password, autocomplete: "off", class: "form-control" %>
    <small>変更しない場合は空のままにしてください。</small>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, "新しいパスワード（確認用）" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :current_password, "現在のパスワード" %> (確認用)<br />
    <%= f.password_field :current_password, autocomplete: "off", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "更新", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "アカウントを削除する", user_registration_path(@user), method: :delete, data: { confirm: "本当にアカウントを削除しますか？" }, class: "btn btn-danger mt-3" %>

<%= link_to "もどる", root_path, class: "btn btn-secondary mt-3" %>